### ISSUE TITLE
Research Heroku Deployment

### ISSUE THREAD

**Issue by dane-johnson** [maryvilledev/codesplain#1]

**Comment by solkaz** [comment]
https://github.com/mars/create-react-app-buildpack

**Comment by Hopding** [comment]
I was able to run the following commands to get a React app up and running on Heroku. I was actually surprised by how easy it was, and that I didn't have to write a single line of configuration code. Unless there is something special which that buildpack provides, I'm not sure that we would need it.
```bash
$ create-react-app test-app
$ cd test-app
$ git init
$ git add .
$ git commit -m 'initial commit'
$ heroku create
$ git push heroku master
$ heroku open
```
