### ISSUE TITLE
Use CircleCI to build parser functions and push to correct S3 bucket/path

### ISSUE THREAD

**Issue by thebho** [maryvilledev/codesplain#15]
On merge to master: overwrite `{language}/dev/{language}.min.js`
On release: add `{language}/{release_version}/{language}.min.js`
Promoting to dev/qa: add a symlink to version number or overwrite the `/qa/`,`/prod/` files

**Comment by dane-johnson** [comment]
http://alignedleft.com/resources/cheap-web-hosting

**Comment by dane-johnson** [comment]
https://pages.github.com/

**Comment by thebho** [comment]
Added codesplain-parsers/python3/v0.1/python3 to S3

**Comment by thebho** [comment]
Updated description
