### ISSUE TITLE
Splain CodeSplain code

### ISSUE THREAD

**Issue by thejoelw** [maryvilledev/codesplain#7]
The readme needs to explain how to setup the project and what each script does. The examples need to show how to use the generated parsers.

**Comment by thejoelw** [comment]
README.md was written in #12. Still need to write examples

**Comment by thejoelw** [comment]
Comment and document code. Make nice graphs.

**Comment by dane-johnson** [comment]
I have reviewed this issue and found it to be an issue.
Docs look a lot better tho.

**Comment by dane-johnson** [comment]
No progress has been made for almost a month. Closing.
