### ISSUE TITLE
LaunchCodeEducation user unable to log in

### ISSUE THREAD

**Issue by chrisbay** [maryvilledev/codesplain#86]
## Expected Behavior

Members of the LaunchCodeEducation org should be able to log in

## Current Behavior

Upon hitting "Log In", I receive the message "Sorry, you are not a member of an organization authorized to use this application."

**Comment by thebho** [comment]
Looks like we had a configuration regression.  I'm working on a fix right now

**Comment by thebho** [comment]
Need to recover the `IGNORE_WHITELIST` logic that was removed
