### ISSUE TITLE
Strings are no longer highlighting from old saved snippets

### ISSUE THREAD

**Issue by thebho** [maryvilledev/codesplain#97]

**Comment by dane-johnson** [comment]
Highlight function as far back as https://github.com/maryvilledev/codesplainUI/commit/934de54549148c21d86b86e1179ea6ae6a362fac has this same bug.

**Comment by dane-johnson** [comment]
That was before tree matchers, so it should be using the same snippets structure as the ones not being parsed now.

**Comment by dane-johnson** [comment]
On the other hand, I am not sure how the issue could be related to the parser, because the parser doesn't run when bringing in an old snippet.
